#!/usr/bin/perl

use v5.20;

use strict;
use warnings;
no warnings qw( experimental::signatures );

use utf8;
use feature qw( signatures );
use open    qw( :std :locale );
use autodie qw( close );

our $VERSION = v0.0.22;

use Config          qw( %Config );
use File::Path      qw( make_path );
use Getopt::Long    qw( :config posix_default permute pass_through auto_version );
use IPC::Open3      qw( open3 );
use Scalar::Util    qw( looks_like_number reftype );
use Symbol          qw( gensym );
use Term::ANSIColor qw( colored coloralias colorstrip );
use Text::Wrap;
use Time::HiRes     qw( gettimeofday tv_interval );

use constant CONFIG_DIR => $ENV{ HOME } . '/.config/gim/';
use constant CONFIG_FILE => CONFIG_DIR . 'config.ini';
use constant PACKAGE_DIR => CONFIG_DIR . 'perl5/';

BEGIN
{
    local $@ = '';
    make_path( CONFIG_DIR );

    # Gim relies on Capture::Tiny, which however is not available on all
    # target platforms (most notably Git Bash on Windows). Unfortunately
    # this platform _also_ lacks the infrastructure to pull the package
    # from CPAN. So we do it manually.
    my $rc = eval
    {
        # Check if package is already available
        require Capture::Tiny;
        Capture::Tiny->import( qw( :all ) );
        1;
    };

    if ( ! $rc )
    {
        # Pull package from GitHub to ~/.config/gim.
        make_path( PACKAGE_DIR . 'Capture' );
        system( 'curl https://raw.githubusercontent.com/dagolden/Capture-Tiny/master/lib/Capture/Tiny.pm -s > ' . PACKAGE_DIR . 'Capture/Tiny.pm' );
        use lib PACKAGE_DIR;
        require Capture::Tiny;
        Capture::Tiny->import( qw( :all ) );
        1;
    }

    $rc = eval
    {
        require Config::IniFiles;
        Config::IniFiles->import();
        1;
    };

    if ( ! $rc )
    {
        make_path( PACKAGE_DIR . 'Config' );
        system( 'curl https://raw.githubusercontent.com/shlomif/perl-Config-IniFiles/master/config-inifiles/lib/Config/IniFiles.pm -s > ' . PACKAGE_DIR . 'Config/IniFiles.pm' );
        use lib PACKAGE_DIR;
        require Config::IniFiles;
        Config::IniFiles->import();
        1;
    }

    if ( exists( $ENV{ CLICOLOR } ) && $ENV{ CLICOLOR } == 0 )
    {
        if ( ! $ENV{ CLICOLOR_FORCE } )
        {
            $ENV{ ANSI_COLORS_DISABLED } = 1;
        }
    }
}

###################################################################
###################################################################
my $E_OK    = 0;
my $E_ERROR = 1;

my %_category =
(
    'info'   => { order => 0, about => 'Obtaining information' },
    'local'  => { order => 1, about => 'Modify local repository' },
    'remote' => { order => 2, about => 'Modify remote repository' }
);
my %_help;  # => category, about, usage, help
my %_topic; # => order, about, help

my @sig_names;
@sig_names[ split( ' ', $Config{ sig_num } ) ] = split( ' ', $Config{ sig_name } );

my $cfg = util::cfg_read();

###################################################################
###################################################################
package util
{
    # Check that the number of arguments remaining in @ARGV
    # is no less than min and no more than max. -1 means no
    # check.
    sub argv_check ( $min, $max )
    {
        dbg::enter();

        if ( @ARGV < $min )
        {
            util::throw(
                util::localize( 'Too few arguments.' ) .
                util::localize( 'Try ‘[_1]’.', 'gim help ' . caller( 0 ) )
            );
        }

        if ( ( $max > -1 ) && ( @ARGV > $max ) )
        {
            util::throw(
                util::localize( 'Too many arguments.' ) .
                util::localize( 'Try ‘[_1]’.', 'gim help ' . caller( 0 ) )
            );
        }

        dbg::leave();
        return;
    }

    # Configuration defaults, if no config.ini is found.
    sub cfg_defaults
    {
        dbg::enter();
        my $defaults = Config::IniFiles->new();

        $defaults->AddSection( 'colorscheme' );
        $defaults->newval( 'colorscheme', 'branch',   'green' );
        $defaults->newval( 'colorscheme', 'current',  'cyan' );
        $defaults->newval( 'colorscheme', 'error',    'red' );
        $defaults->newval( 'colorscheme', 'hash',     'yellow' );
        $defaults->newval( 'colorscheme', 'header',   'bold' );
        $defaults->newval( 'colorscheme', 'line',     'magenta' );
        $defaults->newval( 'colorscheme', 'local',    'green' );
        $defaults->newval( 'colorscheme', 'name',     'cyan' );
        $defaults->newval( 'colorscheme', 'ok',       'green' );
        $defaults->newval( 'colorscheme', 'push',     'blue' );
        $defaults->newval( 'colorscheme', 'ref',      'cyan' );
        $defaults->newval( 'colorscheme', 'remote',   'red' );
        $defaults->newval( 'colorscheme', 'stash',    'yellow' );
        $defaults->newval( 'colorscheme', 'symref',   'green' );
        $defaults->newval( 'colorscheme', 'tag',      'yellow' );
        $defaults->newval( 'colorscheme', 'time',     'blue' );
        $defaults->newval( 'colorscheme', 'upstream', 'yellow' );
        $defaults->newval( 'colorscheme', 'url',      'magenta' );
        $defaults->newval( 'colorscheme', 'warn',     'yellow' );

        $defaults->AddSection( 'options' );
        $defaults->newval( 'options', 'impl_info', '0' );
        $defaults->newval( 'options', 'hash_length', '8' );
        $defaults->newval( 'options', 'graph_width', '6' );
        $defaults->newval( 'options', 'diff', '-U3' );

        dbg::leave();
        return $defaults;
    }

    # Initialize the default configuration, then import config.ini
    # to override defaults. Also, creates color aliases for all
    # entries of [colorscheme].
    sub cfg_read
    {
        dbg::enter();

        # If config.ini does not exist, create empty config.ini.
        # (Config::IniFiles->new() can handle empty file, but not
        # non-existing file.)
        if ( ! -e ::CONFIG_FILE )
        {
            my $cfgfile;

            if ( ! open( $cfgfile, '>', ::CONFIG_FILE ) )
            {
                util::throw(
                    util::localize( 'Could not open ‘[_1]’.', ::CONFIG_FILE ) .
                    $!
                );
            }

            close( $cfgfile );
        }

        # Initialize defaults, load config.ini
        my $config = Config::IniFiles->new( -import => util::cfg_defaults(), -file => ::CONFIG_FILE, -allowempty => 1 );

        # Aliassing colorscheme settings
        foreach ( $config->Parameters( 'colorscheme' ) )
        {
            dbg::msg( "coloralias( '$_', '$config->val( 'colorscheme', $_ )' )" );
            ::coloralias( $_, $config->val( 'colorscheme', $_ ) );
        }

        dbg::leave();
        return $config;
    }

    # Check if the list of arguments violates the predicate
    # given as first parameter. Returns if all arguments
    # check out, throws otherwise.
    # Predicates:
    # FILE, FILEORDIR, TRACKED
    sub filespec_check ( $predicate, @filespec )
    {
        dbg::enter();

        foreach ( @filespec )
        {
            if ( ! -e $_ )
            {
                util::throw(
                    util::localize( '‘[_1]’ does not exist.', $_ )
                );
            }

            if ( ( $predicate eq 'FILE' ) && ( ! -f $_ ) )
            {
                util::throw(
                    util::localize( '‘[_1]’ is not a regular file.', $_ )
                );
            }

            if ( ( $predicate eq 'FILEORDIR' ) && ( ( ( ! -f $_ ) && ( ! -d $_ ) ) || -l $_ ) )
            {
                util::throw(
                    util::localize( '‘[_1]’ is neither regular file nor directory.', $_ )
                );
            }

            if ( $predicate eq 'TRACKED' )
            {
                my @command = ( 'git', 'ls-files', '--error-unmatch', $_ );
                my ( $out, $err, $rc ) = executor::run( \@command, throw_on_fail => 0 );

                if ( $rc != 0 )
                {
                    util::throw(
                        util::localize( '‘[_1]’ is not under version control.', $_ )
                    );
                }
            }
        }

        dbg::leave();
        return;
    }

    # Given a basic message and a list of arguments, this function
    # inserts arguments in place of placeholders '[_1]', '[_2]'
    # etc. in the basic message.
    sub localize ( $msg, @args )
    {
        dbg::enter();

        # Replace ‘[_n]’ with argument #n - 1.
        for ( 1 .. @args )
        {
            $msg =~ s/\[_$_\]/$args[ $_ - 1 ]/;
        }

        dbg::msg( $msg );
        dbg::leave();
        return $msg . "\n";
    }

    sub rc_check ( $rc, $command, $err, %options )
    {
        dbg::enter();

        my %opts = ( throw_on_fail => 1, %options );

        if ( $rc != 0 )
        {
            if ( $rc == -1 )
            {
                util::throw(
                    util::localize( 'Could not execute ‘[_1]’.', ${$command}[0] ) .
                    $err .
                    "\n"
                );
            }

            if ( $rc & 127 )
            {
                util::throw(
                    util::localize( 'Child process died with signal [_1] ‘SIG[_2]’.', $rc, $sig_names[ $rc ] )
                );
            }

            $rc >>= 8;

            if ( $opts{ throw_on_fail } )
            {
                util::throw(
                    util::localize( 'Failure while executing ‘[_1]’.', ${$command}[0] . ' ' . ${$command}[1] ) .
                    $err .
                    "\n"
                );
            }
        }

        dbg::leave();
        return $rc;
    }

    # Pull subcommand from @ARGV.
    # When called from the top level, checks existence of worker
    # class by that name, and returns an instance of that class.
    # When called from a worker class, checks for a function by
    # that name, and returns the name.
    sub subcommand ( $default, %aliases )
    {
        dbg::enter();
        my $caller = caller( 0 );
        my $subcommand;

        if ( @ARGV )
        {
            my $candidate = $aliases{ $ARGV[0] } // $ARGV[0];

            if ( $caller eq 'main' )
            {
                if ( $candidate->isa( 'worker' ) && ! ( $candidate =~ m/worker$/ ) )
                {
                    $subcommand = $candidate;
                    shift( @ARGV );
                }
            }
            else
            {
                if ( $caller->can( $candidate ) )
                {
                    $subcommand = $candidate;
                    shift( @ARGV );
                }
            }

            if ( ! defined( $subcommand ) )
            {
                util::throw( util::localize( 'Unknown command.' ) );
            }
        }
        elsif ( ! defined( $subcommand ) )
        {
            $subcommand = $default;
        }

        if ( $caller eq 'main' )
        {
            $subcommand = $subcommand->new();
        }

        dbg::leave();
        return $subcommand;
    }

    # Throw exception: rc as the error code, msg as exception
    # message.
    sub throw ( $msg )
    {
        $msg = fmt::error( $msg );
        dbg::throw();
        local $! = $E_ERROR;
        die( $msg );
    }
}

###################################################################
###################################################################
package fmt
{
    sub branch ( $str )
    {
        return ::colored( sprintf( '%-20s', $str ), substr( $str, 0, 1 ) eq '*' ? 'current' : 'branch' );
    }

    sub description ( $str )
    {
        return $str;
    }

    sub error ( $str )
    {
        return ::colored( util::localize( 'Error:' ), 'error' ) . ' ' . $str;
    }

    sub graph ( $str )
    {
        my $len = length( ::colorstrip( $str ) );
        my $width = $cfg->val( 'options', 'graph_width' );

        if ( $len < $width )
        {
            $str .= ( ' ' x ( $width - $len ) );
        }

        return ' ' . $str;
    }

    sub hash ( $str )
    {
        return ::colored( $str, 'hash' );
    }

    sub header ( $str )
    {
        return ::colored( $str, 'header' );
    }

    sub linenr ( $str )
    {
        return ::colored( $str, 'line' );
    }

    sub local ( $str )
    {
        return ::colored( sprintf( '  %-20s', $str ), 'local' );
    }

    sub name ( $str )
    {
        return ::colored( sprintf( '%-15.15s', $str ), 'name' );
    }

    sub ok ( $str )
    {
        return ::colored( util::localize( 'OK:' ), 'ok' ) . '  ' . $str;
    }

    sub push ( $str )
    {
        return ::colored( $str, 'push' );
    }

    sub ref ( $str )
    {
        return ::colored( $str, 'ref' );
    }

    sub remote ( $str )
    {
        return ::colored( sprintf( '%12s', $str ), 'remote' );
    }

    sub stash ( $str )
    {
        return ::colored( $str, 'stash' );
    }

    sub symref ( $str )
    {
        return ::colored( $str, 'symref' );
    }

    sub tag ( $str )
    {
        return ::colored( $str, 'tag' );
    }

    sub time ( $str )
    {
        return ::colored( sprintf( '%15s', $str ), 'time' );
    }

    sub upstream ( $str )
    {
        return ::colored( $str, 'upstream' );
    }

    sub url ( $str )
    {
        return ::colored( $str, 'url' );
    }

    sub warning ( $str )
    {
        return ::colored( util::localize( 'Warning:' ), 'warn' ) . ' ' . $str;
    }
}

###################################################################
###################################################################
# Similar to worker::execute(), which provides combined stdout and
# stderr of a command in scalar return values, this class gives
# access to stdout of a command line by line (i.e., as a stream).
#
# $self->{ out } is a stream handle on stdout.
# $self->{ err } is a stream handle on stderr.
# $self->{ errors } will receive a dump of $self->{ err } when
# $self->close_exe() is called.
package executor
{
    sub run ( $command, %options )
    {
        dbg::enter();
        my $out = '';
        my $err = '';
        my $rc;

        if ( defined( $options{ 'interactive' } ) )
        {
            $rc = system( @{$command} );
        }
        else
        {
            ( $out, $err, $rc ) = Capture::Tiny::capture { system( @{$command} ); };
        }

        $rc = util::rc_check( $rc, $command, $err, %options );
        dbg::leave();
        return ( $out, $err, $rc );
    }

    # Requires the command to be executed as parameter.
    sub new ( $class, $command )
    {
        dbg::enter();
        my $self = bless( { command => $command, pid => 0, linecount => 0, err => Symbol::gensym }, $class );
        eval
        {
            $self->{ pid } = IPC::Open3::open3( $self->{ in }, $self->{ out }, $self->{ err }, @{$command} );
            1;
        }
        or do
        {
            dbg::msg( 'Exception thrown by open3()' );
            dbg::msg( $@ );
            util::throw(
                util::localize( 'Failure while executing ‘[_1]’.', ${$command}[0] . ' ' . ${$command}[1] ) .
                $! .
                "\n" );
        };

        dbg::leave();
        return $self;
    }

    # Writes a line of output to $_.
    sub readln ( $self )
    {
        dbg::enter();
        use Encode qw( decode );
        my $fh = $self->{ out };

        if ( defined( $_ = decode( 'UTF-8', readline( $fh ) ) ) )
        {
            ++$self->{ 'linecount' };
        }

        dbg::leave();
        return $_;
    }

    # Closes the stream, writing stderr to $self->{ errors }.
    # This is optional, as the destructor will do it anyway.
    sub close_exe ( $self )
    {
        dbg::enter();

        if ( $self->{ pid } != 0 )
        {
            my $fh = $self->{ err };
            $self->{ errors } = do { local $/ = undef; <$fh> };

            if ( length( $self->{ errors } ) > 0 )
            {
                dbg::msg( "Output on stderr: $self->{ errors }" );
            }

            dbg::msg( "waiting for $self->{ pid }" );
            waitpid( $self->{ pid }, 0 );
            $self->{ pid } = 0;
            $self->{ rc } = util::rc_check( $?, $self->{ command }, $self->{ errors } );
        }

        dbg::leave();
        return;
    }

    DESTROY
    {
        my ( $self ) = @_;
        dbg::enter();
        $self->close_exe();
        dbg::leave();
        return;
    }
}

###################################################################
package logger
{
    use parent -norequire => 'executor';

    sub new ( $class, $logspecs )
    {
        dbg::enter();
        my @command = ( 'git', 'log', '--color=always', '--decorate-refs=HEAD', '--decorate-refs=refs/heads', '--decorate-refs=refs/remotes', '--decorate-refs=refs/stash', '--decorate-refs=refs/tags', '--date-order', '--abbrev=' . $cfg->val( 'options', 'hash_length' ), '--pretty=format:%h%aN%ar%ai%cN%cr%ci%s%C(auto)%d', @{$logspecs} );
        my $self = $class->SUPER::new( \@command );
        dbg::leave();
        return $self;
    }

    sub readln_fmt ( $self )
    {
        dbg::enter();

        if ( defined( $self->SUPER::readln() ) )
        {
            chomp;
            # my ( $graph, $hash, $authorName, $authorTimeRel, $authorTimeIso, $commitName, $commitTimeRel, $commitTimeIso, $subject, $description ) = @{$_};
            my @elements = ( $_ );

            if ( m// )
            {
                @elements = ( m/([^]*)([^]*)([^]*)([^]*)([^]*)([^]*)([^]*)([^]*)([^]*)([^]*)/ );
                dbg::msg( "$elements[0]-$elements[1]" );
            }

            $_ = \@elements;
        }

        dbg::leave();
        return $_;
    }
}

###################################################################
###################################################################
package dbg
{
    my $_dbg;
    my $_indent = 0;
    my $_t0 = [Time::HiRes::gettimeofday];

    # Called from top-level GetOptions() if --debug is specified.
    # Opens file handle $_dbg to write to gim.log.
    sub init ( $, $ )
    {
        if ( ! open( $_dbg, '>', 'gim.log' ) )
        {
            util::throw(
                util::localize( 'Could not open ‘[_1]’.', 'gim.log' ) .
                $!
            );
        }

        return;
    }

    # Get a high-resolution timestamp (so gim.log tells how long
    # operations are taking).
    sub timestamp
    {
        return sprintf( '%07.4f', Time::HiRes::tv_interval( $_t0 ) );
    }

    # Track entry into a subroutine
    sub enter
    {
        if ( defined( $_dbg ) )
        {
            # Using caller() in  DB puts arguments in @DB::args
            package DB;
            my $package  = caller( 0 );
            my $function = ( caller( 1 ) )[3];

            if ( $package eq 'main' )
            {
                $function = substr( $function, length( 'main::' ) );
            }
            elsif ( $package->isa( 'worker' )
                && substr( $function, -length( 'new' ) ) ne 'new' )
            {
                shift( @DB::args );
            }

            my $msg = sprintf( '%s %s>> %s(', dbg::timestamp(), ( ' ' x $_indent ), $function );

            if ( scalar( @DB::args ) && ref( $DB::args[0] ) ne 'GLOB' )
            {
                $msg .= sprintf( ' %s ',
                    join(
                        ', ',
                        map
                        {
                            defined( $_ )
                                ? ( Scalar::Util::looks_like_number( $_ )
                                    ? $_
                                    : ( ( ( Scalar::Util::reftype( $_ ) // '' ) eq 'ARRAY' )
                                        ? "( '" . join( "', '", @{$_} ) . "' )"
                                        : ( ( ( Scalar::Util::reftype( $_ ) // '' ) eq 'HASH' )
                                            ? "SELF"
                                            : qq('$_')
                                        )
                                    )
                                )
                                : '<undef>'
                        } @DB::args
                    )
                );
            }

            $msg .= ')';
            $_indent += 3;
            $msg =~ s/\n/\\n/g;
            say( {$_dbg} $msg );
        }

        return;
    }

    # Write a message into gim.log
    sub msg ( $msg )
    {
        if ( defined( $_dbg ) )
        {
            for ( split( /\n/, $msg ) )
            {
                say( {$_dbg} timestamp() . ' ' . ( ' ' x $_indent ) . $_ );
            }
        }

        return;
    }

    # Track the leaving of a subroutine
    sub leave
    {
        if ( defined( $_dbg ) )
        {
            $_indent -= 3;
        }

        return;
    }

    # Track the throwing of an exception
    sub throw
    {
        $_indent = 0;
        dbg::msg( '<<<<<' );
        return;
    }

    # Close $_dbg on program exit
    END
    {
        if ( defined( $_dbg ) && fileno( $_dbg ) )
        {
            dbg::msg( 'dbg::END' );
            if ( ! close( $_dbg ) )
            {
                util::throw(
                    util::localize( 'Could not close ‘[_1]’.', 'gim.log' ) .
                    $!
                );
            }
        }

        return;
    }
}

###################################################################
###################################################################
# Base class for gim subcommands.
package worker
{
    sub new ( $class )
    {
        dbg::enter();
        my $self = bless( { name => $class }, $class );

        if ( $self->can( 'init' ) )
        {
            $self->init();
        }

        dbg::leave();
        return $self;
    }

    sub init_git_dir ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'rev-parse', '--git-dir' );
        ( $self->{ git_dir }, my $err, my $rc ) = executor::run( \@command );
        dbg::leave();
        return;
    }

    sub init_pager ( $self )
    {
        dbg::enter();

        $Text::Wrap::columns = ( `tput cols 2> /dev/null` || 76 );

        if ( -t STDOUT || -t STDERR )
        {
            open( $self->{ pager }, '|-', 'less -FeRXS' ) || die;
        }

        if ( -t STDOUT )
        {
            open( $self->{ out }, '>&', $self->{ pager } ) || die;
            $self->{ out_paged } = 1;
        }
        else
        {
            $ENV{ 'ANSI_COLORS_DISABLED' } = 1;
            $self->{ out } = \*STDOUT;
        }

        if ( -t STDERR )
        {
            open( $self->{ err }, '>&', $self->{ pager } ) || die;
            $self->{ err_paged } = 1;
        }
        else
        {
            $self->{ err } = \*STDERR;
        }

        dbg::leave();
        return;
    }

    DESTROY
    {
        my ( $self ) = @_;

        if ( defined( $self->{ out_paged } ) )
        {
            close( $self->{ out } );
        }

        if ( defined( $self->{ err_paged } ) )
        {
            close( $self->{ err } );
        }

        if ( defined( $self->{ pager } ) )
        {
            close( $self->{ pager } );
        }

        return;
    }
}

###################################################################
package add
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_pager();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        util::filespec_check( 'FILEORDIR', @ARGV );
        # '--intent-to-add' in combination with 'commit --all'
        # effectively removes staging from the workflow.
        # '--no-all' avoids filesystem deletions resulting in
        # removal from version control, which was considered
        # surprising (a.k.a. 'bad').
        my @command = ( 'git', 'add', '--intent-to-add', '--no-all', '--', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ add } =
{
    category => q{local},
    about => q{Add files to version control},
    usage => q{gim add <filespec> [<filespec> ...]
},
    help => q{Add files to version control.

Earmarks previously untracked files to be included in the next
commit, thereby adding them to version control.

Directories specified as arguments will be added including their
contents, recursively. Adding an empty directory does nothing (as
Git does not store empty directories), but does not generate an
error either.
},
    impl => q{git add --intent-to-add --no-all -- [...]
}};

}

###################################################################
package bisect
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $command = util::subcommand( 'start', 'old' => 'good', 'new' => 'bad' );
        $self->$command();
        dbg::leave();
        return;
    }

    sub start ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'bisect', 'start', '--term-new=new', '--term-old=old', '--first-parent', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub bad ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'bisect', 'new', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub good ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'bisect', 'old', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub skip ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'bisect', 'skip', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub end ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'bisect', 'reset' );

        if ( @ARGV )
        {
            if ( $ARGV[0] eq 'current' || $ARGV[0] eq 'HEAD' )
            {
                push( @command, 'HEAD' );
            }
            elsif ( $ARGV[0] ne '-' )
            {
                util::throw(
                    util::localize( 'Unknown option ‘[_1]’.', $ARGV[0] )
                );
            }
        }
        else
        {
            push( @command, 'bisect/new' );
        }

        executor::run( \@command );
        dbg::leave();
        return;
    }

    # TODO:
    # replay <logfile>
    # log
    # run <cmd>...
    # help

$_help{ bisect } =
{
    category => 'local',
    about => 'Bisect commit history',
    usage => q{gim bisect start [<old-rev> [<new-rev> ...]] -- [<filespec> ...]
   gim bisect new [<rev>]
   gim bisect old [<rev> ...]
   gim bisect skip [<rev> | <rev-range>]
   gim bisect end [- | current]
},
    help => q{Bisect commit history, looking for a specific change.

The ‘bisect’ mode assists with locating the exact commit / code change
that introduced a specific behavior, bug, or feature. You enter this
mode with ‘gim bisect start’, and you leave it with ‘gim bisect end’.

Once in ‘bisect’ mode, you can mark revisions as ‘old’ (i.e., showing
the behavior prior to the change you are looking for), or ‘new’ (i.e.,
showing the behavior after the change you are looking for). Without
argument, ‘gim bisect old’ and ‘gim bisect new’ mark the current
revision. You can also specify a commit hash or a tag to refer to
a different revision.

Once at least one ‘old’ and one ‘new’ revision has been marked, a
revision somewhere in between those two is checked out, so you can
test if that revision shows ‘old’ or ‘new’ behavior, and mark the
revision as such. If your results are indeterminate, you can use
‘gim bisect skip’ to select a different revision.

Either way, a new revision will be checked out for you to test,
bisecting the commit history until you have found the revision you
are looking for.

You can then end ‘bisect’ mode with ‘gim bisect end’, which will
leave ‘bisect’ mode with the first revision marked ‘new’ checked
out; or ‘gim bisect end -’, which will return to the revision
you started the ‘bisect’ from; or ‘gim bisect end current’, which
will leave ‘bisect’ mode with the current revision checked out.
},
    impl => q{Mostly just wrapping ‘git bisect’ and its subcommands.
‘start’ uses ‘--first-parent’, and instead of ‘bisect reset’, we
use ‘bisect end’.
}};

}

###################################################################
package blame
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_pager();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        util::filespec_check( 'TRACKED', @ARGV );
        my @command = ( 'git', 'blame', @ARGV );
        my $exe = executor->new( \@command );
        my $lasthash = '';
        my $linecol = 0;

        while ( $exe->readln() )
        {
            if ( m/^([[:xdigit:]^]*) (.*)\((.*?) (\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2} .\d{4})( *\d*)\)(.*)/ )
            {
                if ( $1 ne $lasthash )
                {
                    $linecol = ( $linecol ) ? 0 : 1;
                }

                printf( {$self->{ out }}
                    "%s %s%s %s%s)%s\n",
                    fmt::hash( $1 ),
                    $2,
                    fmt::name( $3 ),
                    fmt::time( $4 ),
                    ( $linecol ) ? fmt::linenr( $5 ) : $5,
                    $6
                );

                $lasthash = $1;
            }
            else
            {
                util::throw(
                    util::localize( 'Unexpected output by git:' ) .
                    $_
                );
            }
        }

        $exe->close_exe();
        dbg::leave();
        return;
    }

$_help{ blame } =
{
    category => q{info},
    about => q{Show who authored what in a file},
    usage => q{gim blame ...
},
    help => q{Show who authored what in a file.

Annotates each line of a given source file with information on who
modified it last, when, and with which commit.
},
    impl => q{A thin layer around ‘git blame’, adding coloring to
the line number column to highlight block changes.
}};

}

###################################################################
package chmod
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_pager();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $mode = shift( @ARGV );
        util::filespec_check( 'TRACKED', @ARGV );
        my @command = ( 'chmod', $mode, @ARGV );
        executor::run( \@command );
        @command = ( 'git', 'update-index', '--chmod=' . $mode, '--', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ chmod } =
{
    category => q{local},
    about => q{Change permissions on file(s)},
    usage => q{gim chmod <mode> <filespec> [<filespec> ...]
},
    help => q{Change permissions on file(s).

This command is usually used to set or remove the executable bit.
},
    impl => q{‘git update-index --chmod=<mode> -- [...]’
}};

}

###################################################################
package clone
{
    use parent -norequire => 'worker';

    sub run ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'clone', '--quiet', '--no-local', '--', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ clone } =
{
    category => q{local},
    about => q{Clone a repository},
    usage => q{gim clone <URL|filespec>
},
    help => q{Clone a repository.

Creates a clone of the specified repository.
},
    impl => q{‘git clone --quiet --no-local -- [...]’
}};

}

###################################################################
package commit
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_pager();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $amend;
        my $patch;
        my $file;
        my $msg;
        ::GetOptions(
            'amend' => \$amend,
            'patch' => \$patch,
            'file|F=s' => \$file,
            'message|m=s' => \$msg
        );

        if ( defined( $file ) && defined( $msg ) )
        {
            util::throw(
                util::localize( 'Conflicting options ‘[_1]’ and ‘[_2]’.', '--file', '--message' )
            );
        }

        my @command = ( 'git', 'commit', '--quiet' );

        if ( defined( $amend ) )
        {
            push( @command, '--amend' );
        }

        if ( defined( $patch ) )
        {
            push( @command, '--patch' );
        }

        if ( defined( $file ) )
        {
            push( @command, '--file', $file );
        }

        if ( defined( $msg ) )
        {
            push( @command, '--message', $msg );
        }

        if ( @ARGV )
        {
            util::filespec_check( 'TRACKED', @ARGV );
            push( @command, '--', @ARGV );
        }
        else
        {
            push( @command, '--all' );
        }

        executor::run( \@command, interactive => ! ( defined( $file ) || defined( $msg ) ) );
        dbg::leave();
        return;
    }

$_help{ commit } =
{
    category => q{local},
    about => q{Commit changes to local repository},
    usage => q{gim commit [--amend] [--patch] [<filespec> ...]
   gim commit [--amend] [--patch] [--message | -m <msg>] [<filespec> ...]
   gim commit [--amend] [--patch] [--file | -F <filename>] [<filespec> ...]
},
    help => q{Commit changes to the local repository.

The first variant opens an editor for you to enter the commit
message.

The second variant uses the passed string as the commit message.

The third variant uses the contents of the specified file as the
commit message.

If the ‘--amend’ option is specified, the last commit (which must
not have been published yet) will be amended instead of creating a
new commit.

If the ‘--patch’ option is specified, the user will be queried
which parts of the file(s) he wants to commit.
},
    impl => q{‘git commit [...]’, with ‘--all’ assumed if no files
are specified.
}};

}

###################################################################
package diff
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        $self->init_pager();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $opts = $cfg->val( 'options', 'diff' );
        my @command = ( 'git', 'diff', '--color=always', '--src-prefix=src: ', '--dst-prefix=dst: ', $cfg->val( 'options', 'diff' ), @ARGV );
        my $exe = executor->new( \@command );

        while ( $exe->readln() )
        {
            print( {$self->{ out }} $_ );
        }

        $exe->close_exe();
        dbg::leave();
        return;
    }

$_help{ diff } =
{
    category => q{info},
    about => q{Show differences},
    usage => q{gim diff [<revspec>] [<filespec> [<filespec> ...]]
},
    help => q{Shows differences between commits, commits and the
working copy, etc.

By default shows the difference of the working directory to the
latest commit. By specifying a single revspec, shows the difference
of the working directory to that revspec instead. By specifying two
revspecs, shows the difference between the two revspecs.

By specifying filespecs, limits the diffs shown to those in the
specified files.
},
    impl => q{‘git diff [...]’, with prefixes ‘src:’ and ‘dst:’
instead of ‘a/’ and ‘b/’, and honoring options.diff from the config
file (defaulting to ‘-U3’).
}};

}

###################################################################
package fetch
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        $self->init_pager();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $quiet;
        ::GetOptions(
            'quiet|q' => \$quiet
        );

        my @tags;
        my @command = ( 'git', 'for-each-ref', '--format="%(objecttype)%(refname:lstrip=2)%(objectname)"', 'refs/tags/*' );
        my $exe = executor->new( \@command );

        while ( $exe->readln() )
        {
            chomp;
            my ( $type, $name, $hash ) = split( '\x{1f}' );

            if ( $type eq 'commit' )
            {
                dbg::msg( "Saving lightweight tag \"$name $hash\"" );
                push( @tags, "$name $hash" );
            }
        }

        $exe->close_exe();

        dbg::msg( 'Fetching from remote, pruning tags' );
        @command = ( 'git', 'fetch', '--all', '--quiet', '--prune', '--prune-tags' );
        executor::run( \@command );

        foreach ( @tags )
        {
            dbg::msg( "Re-applying lightweight tag \"$_\"" );
            @command = ( 'git', 'tag', $_ );
            executor::run( \@command );
        }

        print( {$self->{ out }} util::localize( 'Local repository up to date.' ) );

        if ( ! defined( $quiet ) )
        {
            $self->init_status();
            $self->init_ahead_behind();
            bless( $self, 'status' );
            local @ARGV = ();
            $self->run();
        }

        dbg::leave();
        return;
    }

$_help{ fetch } =
{
    category => 'remote',
    about => 'Fetch changes from upstream',
    usage => q{gim fetch
},
    help => q{Fetch changes from upstream(s).

No changes will be applied to your working copy yet.

Annotated tags that no longer exist upstream get deleted locally.
(See ‘gim help tag’.)
},
    impl => q{‘git fetch --all --quiet --prune --prune-tags’, with
backing up and re-applying lightweight tags.
}};

}

###################################################################
package help
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_pager();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $subject = 'help';

        if ( @ARGV == 0 || $ARGV[0] eq 'topics' )
        {
            $self->help();
        }
        else
        {
            $subject = shift( @ARGV );

            if ( defined( $_topic{ $subject } ) )
            {
                $self->help_on_topic( $subject );
            }
            elsif ( defined( $_help{ $subject } ) )
            {
                $self->help_on_command( $subject );
            }
            else
            {
                util::throw(
                    util::localize( 'No help available for ‘[_1]’.', $subject )
                );
            }
        }

        dbg::leave();
        return;
    }

    sub help ( $self )
    {
        dbg::enter();
        print( {$self->{ out }}
            "\n" .
            ' ' . fmt::header( util::localize( 'Usage:' ) ) .
            ( ( @ARGV == 0 ) ? "   gim help <subcommand>\n" : "" ) .
            "   gim help <topic>\n\n" .
            ( ( @ARGV == 0 ) ? ' ' . fmt::header( util::localize( 'Available subcommands:' ) ) . "\n" : "" )
        );

        if ( @ARGV == 0 )
        {
            # List each category in their sort order
            foreach my $category ( sort { $_category{ $a }{ order } <=> $_category{ $b }{ order } } keys %_category )
            {
                print( {$self->{ out }}
                    '   ' . fmt::header( util::localize( $_category{ $category }{ about } ) )
                );

                # List the commands alphabetically
                foreach my $command ( sort keys %_help )
                {
                    # Filter for commands of the current category
                    if ( $_help{ $command }{ category } eq $category )
                    {
                        printf( {$self->{ out }}
                            "     gim %-19s %s\n", $command, $_help{ $command }{ about }
                        );
                    }
                }

                print( {$self->{ out }} "\n" );
            }
        }

        print( {$self->{ out }}
            ' ' . fmt::header( util::localize( 'Available topics:' ) ) .
            "\n"
        );

        foreach my $topic ( sort { $_topic{ $a }{ order } <=> $_topic{ $b }{ order } } keys %_topic )
        {
            printf( {$self->{ out }}
                "     %-23s %s\n", $topic, $_topic{ $topic }{ about }
            );
        }

        dbg::leave();
        return;
    }

    sub help_on_topic ( $self, $topic )
    {
        dbg::enter();
        print( {$self->{ out }}
            "\n" .
            ' ' . fmt::header( $_topic{ $topic }{ about } ) .
            "\n\n" .
            Text::Wrap::fill( ' ', ' ', $_topic{ $topic }{ help } )
        );
        dbg::leave();
        return;
    }

    sub help_on_command ( $self, $command )
    {
        dbg::enter();
        print( {$self->{ out }}
            "\n" .
            ' ' . fmt::header( util::localize( 'Usage:' ) ) .
            '   ' . $_help{ $command }{ usage } .
            "\n" .
            Text::Wrap::fill( ' ', ' ', $_help{ $command }{ help } )
        );

        if ( $cfg->val( 'options', 'impl_info' ) eq '1' )
        {
            print( {$self->{ out }}
                "\n\n" .
                ' ' . fmt::header( util::localize( 'Implementation:' ) ) .
                "\n" .
                Text::Wrap::fill( ' ', ' ', $_help{ $command }{ impl } )
            );
        }

        dbg::leave();
        return;
    }

$_help{ help } =
{
    category => q{info},
    about => q{Help system},
    usage => q{gim help [<subject>]
},
    help => q{Gim help system.

Gim does not come with separate documentation, but its own help
system.

With ‘gim help’ you get an overview of available subcommands and
help topics.

With ‘gim help <subject>’ you get help on a specific subject, which
can be either a subcommand, or a general help topic (which are not
linked to any specific subcommand).
},
    impl => q{Custom.
}};

}

###################################################################
package init
{
    use parent -norequire => 'worker';

    sub run ( $self )
    {
        dbg::enter();
        my $local = 0;
        ::GetOptions(
            'local|l' => sub { $local = 1; },
            'bare|b' => sub { $local = 0; }
        );
        my $repo = shift( @ARGV );

        if ( -e $repo )
        {
            util::throw(
                util::localize( '‘[_1]’ already exists.', $repo )
            );
        }

        my @command = ( 'git', 'init', '--quiet' );

        if ( $local != 1 )
        {
            push( @command, '--bare' );
        }

        push( @command, '--', $repo );
        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ init } =
{
    category => q{local},
    about => q{Initialize a new repository},
    usage => q{gim init [--bare|-b] <filespec>
   gim init <--local|-l> <filespec>
},
    help => q{Initialize a new repository.

With the option ‘--bare’ (the default), the new repository will
have no working directory; its purpose will be to be cloned, with
actual work being done in the clones.

With the option ‘--local’, a local repository including working
directory will be set up. This is only recommended for strictly
local use, i.e. for repositories that will not be cloned.
},
    impl => q{git init --quiet [--bare] -- [...]
}};

}

###################################################################
package log
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_pager();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $print_graph;
        my @specs = ();
        my $predefined = 0;
        ::GetOptions(
            "all|a" => sub { push( @specs, '--all' ); },
            "short|s" => sub { push( @specs, '--format=short' ); $predefined = 1; },
            "medium|m" => sub { push( @specs, '--format=medium' ); $predefined = 1; },
            "long|l" => sub { push( @specs, '--format=full' ); $predefined = 1; },
            "verbose|v" => sub { push( @specs, '--format=fuller' ); $predefined = 1; },
            "reference|r" => sub { push( @specs, '--format=reference' ); $predefined = 1; },
            "graph|g" => sub { push( @specs, '--graph' ); $print_graph = 1; }
        );

        push( @specs, @ARGV );
        my $log = logger->new( \@specs );

        while ( $predefined ? $log->readln() : $log->readln_fmt() )
        {
            my $line;

            if ( $predefined )
            {
                # Predefined format, leave alone
                chomp;
                $line = $_ . "\n";
            }
            else
            {
                # Custom format
                if ( scalar( @{$_} ) == 1 )
                {
                    $line = ' ' . ${$_}[0] . "\n";
                }
                else
                {
                    my ( $graph, $hash, $authorName, $authorTimeRel, $authorTimeIso, $commitName, $commitTimeRel, $commitTimeIso, $subject, $description ) = @{$_};
                    $line =
                        ( $print_graph ? fmt::graph( $graph ) : ' ' ) .
                        fmt::hash( $hash ) . '  ' .
                        fmt::time( $authorTimeIso ) . '  ' .
                        fmt::name( $authorName ) . '  ' .
                        $subject . '  ' .
                        fmt::description( $description ) . '  ' .
                        "\n";
                }
            }

            print( {$self->{ out }} $line );
        }

        $log->close_exe();
        dbg::leave();
        return;
    }

$_help{ log } =
{
    category => q{info},
    about => q{Show a commit log},
    usage => q{gim log [option]
},
    help => q{Show a commit log.

By default, shows a one-line format containing relative time,
author information, commit summary, and tree references.

The ‘--graph’ / ‘-g’ option adds a branch graph to the output of
any log output.

The remaining options correspond to predefined log formats
generated by the Git backend.

The options ‘--reference’ / ‘-r’, ‘--short’ / ‘-s’, and ‘--medium’
/ ‘-m’ correspond to the ‘git log --format=...’ options of the same
name.

The ‘--long’ / ‘-l’ option corresponds to ‘git log --format=full’.

The ‘--verbose’ / ‘-v’ option corresponds to ‘git log --format=fuller’.

The ‘--tags / -t’ option shows (both lightweight and annotated) tags.

The ‘--all / -a’ option shows a log of all branches, not just the
current one.
},
    impl => q{‘git log --date-order’, with ‘--decorate-refs=...’ for
‘HEAD’, ‘refs/heads’, ‘refs/remotes’, and ‘refs/stash’ respectively.

Output is reformatted for readability.
}};

}

###################################################################
package mkbranch
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'branch', '--', $ARGV[0] );
        executor::run( \@command );
        $command[1] = 'switch';
        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ mkbranch } =
{
    category => q{local},
    about => q{Create a new branch},
    usage => q{gim mkbranch <branch>
},
    help => q{Create a new branch.

Creates a new branch, including switching to it.
},
    impl => q{Currently really just a dummy forwarding to ‘git
branch -- [...]’, followed by ‘git switch -- [...]’.
}};

}

###################################################################
package mv
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my @from_specs = @ARGV;
        pop( @from_specs );
        util::filespec_check( 'TRACKED', @from_specs );
        my @command = ( 'git', 'mv', '--', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ mv } =
{
    category => q{local},
    about => q{Move / rename file(s)},
    usage => q{gim mv <filespec> <filespec>
   gim mv <filespec> [<filespec> ...] <dirspec>
},
    help => q{Move / rename file(s).

Moves / renames a file, or moves multiple files to a target
directory.
},
    impl => q{Wrapper for ‘git mv --’.
}};

}

###################################################################
package revert
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $clean;
        ::GetOptions(
            'clean|c' => \$clean
        );
        my @command = ( 'git', 'reset', '--', @ARGV );
        executor::run( \@command );
        $command[1] = 'restore';
        # This silences all fails, but is necessary to avoid errors
        # when the adding of files has been reset. A better choice
        # would be checking @ARGV for files that are still tracked.
        executor::run( \@command, throw_on_fail => 0 );

        if ( defined( $clean ) )
        {
            splice( @command, 1, 1, 'clean', '--force', '-d', '--quiet' );
            executor::run( \@command );
        }

        dbg::leave();
        return;
    }

$_help{ revert } =
{
    category => q{local},
    about => q{Revert local changes},
    usage => q{gim revert [--clean|-c] <filespec> [<filespec> ...]
},
    help => q{Revert local changes.

Reverts local changes to the checked-in state. With the ‘--clean’
option, untracked files will be deleted as well.
},
    impl => q{‘git reset -- [...]’ followed by ‘git restore --
[...]’.

The ‘--clean’ option adds ‘git clean --force -d --quiet [...]’.
}};

}

###################################################################
package rm
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'rm' );
        ::GetOptions(
            'recurse|r' => sub { push( @command, '-r' ); },
            'force|f' => sub { push( @command, '-f' ); }
        );
        util::filespec_check( 'TRACKED', @ARGV );
        push( @command, '--', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ rm } =
{
    category => q{local},
    about => q{Remove file(s) from version control},
    usage => q{gim rm [--recurse|-r] [--force|-f] <filespec> [<filespec> ...]
},
    help => q{Remove file(s) from version control.

Removes one or more files from version control. If one or more of
the given <filespec> refers to a directory, the ‘--recurse’ / ‘-r’
option is required to remove all the directory contents from version
control.
},
    impl => q{A wrapper for ‘git rm’.
}};

}

###################################################################
package rmbranch
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my @command = ();
        my $remote;
        ::GetOptions(
            'remote|r=s' => \$remote
        );

        if ( defined( $remote ) )
        {
            @command = ( 'git', 'push', $remote, '--delete', $ARGV[0] );
        }
        else
        {
            @command = ( 'git', 'branch', '--delete', '--force', '--', $ARGV[0] );
        }

        executor::run( \@command );
        dbg::leave();
        return;
    }

$_help{ rmbranch } =
{
    category => q{local},
    about => q{Remove a branch},
    usage => q{gim rmbranch <branch>
   gim rmbranch [--remote | -r <remote>] <branch>
},
    help => q{Remove a branch.

Removes a branch. By default this applies to the local repository.
With the ‘--remote’ option, a branch can be deleted from a remote
repository.
},
    impl => q{A wrapper for ‘git branch --delete --force -- [...]’
or ‘git push [...] --delete [...]’ respectively.
}};

}

###################################################################
package stash
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_pager();
        $self->init_status();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my $command = util::subcommand( 'push' );
        $self->$command();
        dbg::leave();
        return;
    }

    sub apply ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'stash', 'apply', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub branch ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'stash', 'branch', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub clear ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'stash', 'clear', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub drop ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'stash', 'drop', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub list ( $self )
    {
        dbg::enter();
        printf( {$self->{ out }} ' ' . util::localize( 'Stashed:' ) );

        if ( ! defined( $self->{ stash } ) )
        {
            printf( {$self->{out}} '    ' . fmt::stash( util::localize( 'None' ) ) );
            return;
        }

        my @command = ( 'git', 'stash', 'list', @ARGV );
        my $exe = executor->new( \@command );

        while ( $exe->readln() )
        {
            my ( $id, $branch, $commit, $msg ) = ( m/stash\@\{(.*)\}: WIP on ([^:]*): ([a-f0-9]*) (.*)/ );

            if ( defined( $commit ) )
            {
                $msg = fmt::hash( $commit ) . ' ' . $msg;
            }
            else
            {
                ( $id, $branch, $msg ) = ( m/stash\@\{(.*)\}: On ([^:]*): (.*)/ );
            }

            printf( {$self->{ out }}
                "    %s: %s: %s\n",
                fmt::stash( $id ),
                fmt::branch( $branch ),
                $msg
            );
        }

        $exe->close_exe();
        dbg::leave();
        return;
    }

    sub pop ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'stash', 'pop', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub push ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'stash', 'push', '--include-untracked', @ARGV );
        executor::run( \@command );
        dbg::leave();
        return;
    }

    sub show ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'stash', 'show', '--include-untracked', '--patch', @ARGV );
        my $exe = executor->new( \@command );

        while ( $exe->readln() )
        {
            print( {$self->{ out }} $_ );
        }

        $exe->close_exe();
        dbg::leave();
        return;
    }

$_help{ stash } =
{
    category => q{local},
    about => q{Stash away local changes},
    usage => q{gim stash push ...
   gim stash list ...
   gim stash show ...
   gim stash drop ...
   gim stash clear ...
   gim stash apply ...
   gim stash pop ...
   gim stash branch ...
},
    help => q{Stash away local changes.

The following subcommands are available:

 * push   -- Push local commits on the stash stack.

 * list   -- List the stash stack.

 * show   -- Inspect one entry on the stash stack.

 * drop   -- Remove an entry from the stash stack.

 * clear  -- Remove all entries from the stash stack.

 * apply  -- Apply an entry from the stash stack to the working directory.

 * pop    -- As ‘apply’, but removes the entry from the stash stack if applying did not result in errors.

 * branch -- Turn a stash entry into a new branch.
},
    impl => q{Mostly just a wrapper for ‘git stash [...]’ with
‘push’ being made the implicit default.

The ‘push’ subcommand adds ‘--include-untracked’.

The ‘list’ command uses a more readable format.

The ‘show’ command adds ‘-p’.
}};

}

###################################################################
package switch
{
    use parent -norequire => 'worker';

    sub init ( $self )
    {
        dbg::enter();
        $self->init_git_dir();
        dbg::leave();
        return;
    }

    sub run ( $self )
    {
        dbg::enter();
        my @command = ( 'git', 'switch' );
        ::GetOptions(
            'detach|d' => sub { push( @command, '--detach' ); }
        );
        util::argv_check( 1, 1 );
        push( @command, '--', $ARGV[0] );
        my ( $out, $err, $rc ) = executor::run( \@command );

        if ( $rc == 128 )
        {
            @command = ( 'git', 'rev-parse', $ARGV[0] . '^{commit]' );
            ( $out, $err, $rc ) = executor::run( \@command );

            if ( $rc == 0 )
            {
                util::throw(
                    util::localize( '‘[_1]’ is a commit, not a branch. Forgot ‘--detach’?', $ARGV[0] ) .
                    util::localize( 'Try ‘[_1]’.', 'gim help switch' )
                );
            }
        }

        if ( $rc != 0 )
        {
            util::throw(
                util::localize( 'Failure while executing ‘[_1]’.', 'gim switch' ) .
                util::localize( '‘[_1]’ returned ‘[_2]’:', 'gim switch', $rc ) .
                $err . "\n"
            );
        }

        dbg::leave();
        return;
    }

$_help{ switch } =
{
    category => q{local},
    about => q{Switch HEAD to a different commit},
    usage => q{gim switch <branch>
   gim switch [--detach|-d] <commit|tag>
   gim switch -
},
    help => q{Switch HEAD to a different commit.

The first variant switches your HEAD to a different branch.

The second variant switches your HEAD to a specific commit. This
leaves you in “detached HEAD” state, which is why it requires the
extra ‘-d’ / ‘--detach’ option as safeguard against landing you in
this mode by accident. (Check ‘gim help navigation’ for more
information on “detached HEAD” state.)

The third variant is an undo for the last switch, i.e. you switch
back to wherever it was you came from. (Like ‘cd -’ in the shell.)
},
    impl => q{Basically a wrapper around ‘git switch’.
}};

}

###################################################################
###################################################################
# Help Topics
$_topic{ intro } =
{
    order => 1,
    about => q{Introduction to 'Git for Mortals'},
    help => q{Gim is an attempt at providing users with a nicer
command line interface to the version control software Git.

https://github.com/DevSolar/gim

It was written by Martin Baute, <solar@rootdirectory.de>, and is
provided as free software under Creative Commons CC0 1.0 Universal.

https://creativecommons.org/publicdomain/zero/1.0/

Gim is written in Perl, and great care has been taken to ensure
that it runs in Git Bash for Windows (which does not cater for
installing additional modules as dependencies). It should run fine
anywhere Git itself runs, including Git Bash, Cygwin, and native
Bash on both Linux and Android.
}};

$_topic{ simplicity } =
{
    order => 2,
    about => q{How Gim tries to be simpler},
    help => q{Git was written as a power tool for repository
maintainers, then got more options for more diverse workflows,
and unfortunately it never received the reworking and polish it
should have.

For one, Git offers extensive pretty-printing options, yet
by default uses rather unappealing formatting on most of its
commands. There is technical data cluttering the output of
e.g. ‘pull’ or ‘push’, unnecessary verboseness to ‘status’,
and the default output of ‘log’ is dismal.

Gim attempts to prune Git output of unnecessary details, to
format output in a way easily skimmed at a glance, and to make
use of colors to improve legibility.

Some frequently used Git functions hide behind somewhat less
than intuitive combinations of commands and options. Plus,
some features of Git are rather confusing to newcomers, both
without previous VCS knowledge and those coming from e.g.
Subversion or Perforce. One example would be the whole concept
of Staging, which Git documentation also refers to as “the
Index File” in places to confuse you even further.

A side effect of this is that Git documentation, like manual
pages or the built-in help, is lengthy, confusing, and quite
often merely cross-referencing yet other documentation. This
can be quite irritating.

Gim trims down (some would say ruthlessly) on the number of
available options, without compromising too much on functionality.
The commands you will be using dozens of times a day should be
short, easily memorized mnemonics without requiring extra options.

Gim has consciously decided to rename some specific commands
to cater for the more common (and less surprising) use case,
e.g. using ‘revert’ to refer to the reverting of local changes,
not reverting commits by making another commit.

Gim provides documentation for all its commands through ‘gim
help’, and tries to keep things short and to the point, so you
can go back to programming as soon as possible.
}};

$_topic{ safety } =
{
    order => 3,
    about => q{How Gim tries to be safer},
    help => q{There are several features to Git that are, to put
it mildly, flirting with desaster. This is because Git, unlike
many other versioning tools, explicitly allows removing or
overwriting information, even from commits that had been made
long ago. Or get you swamped in the middle of a multi-command
workflow with very few hints on what is going on, or how to
recover from there gracefully.

While some of these features are actually quite useful, the way
Git communicates about those -- or rather, does not communicate
in time -- can be daunting. A good rule of thumb for beginners
is to stay away from any command beginning with ‘re...’, and to
use ‘--force’ only after asking someone more experienced.

Gim tries to be more up-forward with information, especially in
multi-command workflows and potentially damaging operations. As
a rule of thumb, Gim will always ask you before doing anything
that might destroy data.

In other areas, Gim combines multi-command workflows into fewer
commands, or even a single one, while adding safeguards and
double-checks to keep you from derailing.
}};

$_topic{ navigation } =
{
    order => 4,
    about => q{Commits, Tags, Branches, Navigation},
    help => q{To understand several more advanced topics, it is
necessary to understand how a repository is being navigated.

Every commit in the repository is identified by a 160-bit hash.
Any existing commit can be addressed by that hash.

Since hash values are somewhat cumbersome, commits that you would
routinely want to navigate to can be tagged with plain text names
for ease of reference. (Check out the ‘gim tag’ subcommand and
the ‘tags’ help topic.)

A branch is a special tag that gets moved along as you make new
commits.

The current commit also can be referred to by a special tag,
‘HEAD’.

Every commit (except the very first one) has at least one “parent”
commit. (Merge commits have more than one.) You can always move
“up” the commit chain along the parental line, but you cannot move
“down”. (A commit knows its parent(s), but not its childs.)

This results in a special case if you navigated to a commit that
is not a branch head: Git can only “see” the current commit
(“HEAD”) and its parents. Git calls this state “detached HEAD”.

Should you make a commit now, that would not be placed “in line”
with any branch, but basically your ‘HEAD’ would now be pointing
at a new branch head that has no name so far.

You can assign a branch name to your current ‘HEAD’ (‘mkbranch’),
or move back to one of the branch heads.
}};

$_topic{ rewrite } =
{
    order => 5,
    about => q{Rewriting history},
    help => q{Certain features of Gim allow overwriting the commit
history. This has pros and cons.

Unneeded branches can be deleted, confusing merge histories can be
cleaned up, and several individual commits can be squashed into
one, to name just a few pros.

There are three significant cons, however.

The information “cleaned up” this way will be lost. And anyone who
has already cloned (or pulled) the previous version(s) might get
confused when the next pull changes the basis for their edits.

And, probably most nefarious of them all, rewriting history wipes
out any tags applied to any of the commits affected by the rewrite.
Basically, if anything is changed about a commit -- including the
hash code of its parent -- it is no longer the commit that had been
tagged, but a different commit, and any tag on it is lost.

Gim draws the line at changing “public” history. While there will
be no extra warnings when you rewrite local history, Gim will warn
and request additional confirmation from you when a command would
affect history that has already been pushed upstream.
}};

$_topic{ workflows } =
{
    order => 6,
    about => q{How Gim tries to help with workflows},
    help => q{Gim documents a number of common workflows. This
is mostly aimed at newcomers, who are not sure how to do things
yet.

There is no claim that these workflows are described in the best
way, let alone the “one right” way. But they are described in a
simple way, in terms of available Gim commands.
}};

$_topic{ tags } =
{
    order => 7,
    about => q{How Gim makes tags useful},
    help => q{THe default behavior of Git when it comes to tags is
somewhat unintuitive, and not really useful. Gim has the proper
options in place to make them useful:

- annotated tags get pushed automatically (but not lightweight
ones).

- annotated tags get pruned on pulling (i.e., annotated tags that
do not exist remotely get removed from your local repository).

- lightweight tags do not get pruned (actually, they are saved and
re-applied during a pull).

This allows you to use annotated tags for sharing tags with others,
and lightweight tags for local use, without requiring any special
attention other than setting or deleting them through ‘gim tag’.

Note that using git commands on your local repository might handle
tags in ways not consistent with this concept. Refer to the git
documentation for details.
}};

###################################################################
###################################################################
my $command;

# Global program options
::GetOptions(
    'debug'  => \&dbg::init,
    'help|h|?' => \$command
);

# If required by testdriver, return like a module, do not run like
# a program.
if ( $0 eq './testgim' )
{
    return 1;
}

if ( defined( $command ) )
{
    $command = help->new();
}
else
{
    $command = util::subcommand( 'help' );
}

$command->run();

exit $E_OK;
