#!/usr/bin/perl

use v5.20;

use feature      qw( signatures );
no warnings      qw( experimental::signatures );
use utf8;

unshift( @ARGV, '--debug' );

use File::Path qw( make_path remove_tree );

use constant CONFIG_DIR => $ENV{ HOME } . '/.config/gim/';
use constant PACKAGE_DIR => CONFIG_DIR . 'perl5/';
use constant TESTDIR => '.testgim.dir';

BEGIN
{
    remove_tree( TESTDIR );

    local $@ = '';
    make_path( CONFIG_DIR );

    my $rc = eval
    {
        require Carp::Assert::More;
        Carp::Assert::More->import();
        1;
    };

    if ( ! $rc )
    {
        # Pull package from GitHub to ~/.config/gim.
        make_path( PACKAGE_DIR . 'Carp/Assert' );
        system( 'curl -L -f -s https://raw.githubusercontent.com/petdance/carp-assert-more/refs/heads/dev/More.pm > ' . PACKAGE_DIR . 'Carp/Assert/More.pm' );
        use lib PACKAGE_DIR;
        require Carp::Assert::More;
        Carp::Assert::More->import();
        1;
    }
}

require './gim';

########################################

my $str;
my $val;
my $exe;
my $out;
my $err;
my $rc;
my @command;

package testclass
{
    use parent -norequire => 'worker';
    sub run ( $, $ )
    {
        dbg::enter();
        dbg::leave();
        return;
    }
}

package testsuperclass
{
    use parent -norequire => 'worker';

    sub run ( $self )
    {
        dbg::enter();
        my $command = util::subcommand( 'function' );
        $self->$command();
        dbg::leave();
        return;
    }

    sub function ( $ )
    {
        dbg::enter();
        dbg::leave();
        return;
    }
}

sub assert_throw( $cmd, $msg )
{
    $cmd = $cmd . '; 1;';

    if ( eval $cmd )
    {
        $msg =~ s/\n/\\n/g;
        assert_fail( 'Exception expected: "' . $msg . '"' );
    }
    else
    {
        assert_is( $@, $msg );
    }

    return;
}

sub assert_nothrow( $cmd )
{
    $cmd = $cmd . '; 1;';

    if ( ! eval $cmd )
    {
        assert_fail( 'Unexpected exception:' . "\n" . $@ );
    }

    return;
}

sub write_to_file( $filename, $str )
{
    open( my $fh, '>', $filename ) or assert_fail( 'Opening ' . $filename . ' failed.' );
    print( $fh $str ) or assert_fail( 'Writing to ' . $filename . ' failed.' );
    close( $fh ) or assert_fail( 'I/O error on closing ' . $filename );
    undef( $fh );
    return;
}

########################################
say( 'Running tests (check gim.log).' );
########################################

mkdir( TESTDIR );
write_to_file( TESTDIR . '/foo', '' );
write_to_file( TESTDIR . '/eecho', 'my $e = (@ARGV && $ARGV[0] eq "-e") ? shift(@ARGV) : ""; my $s = join(" ", @ARGV); if ($e) { $s =~ s/\\\\n/\\n/g; } print STDERR $s, "\\n";' );

##############################
dbg::msg( '=== throw() ===' );
##############################

assert_throw( "util::throw( \"Zero\\n\" )", ::colored( "Error:\n", 'red' ) . " Zero\n" );
dbg::msg( q{>> util::localize( 'Error:' ) # expected} );
dbg::msg( q{   Error: # expected} );
dbg::msg( q{<<<<< # expected} );

#################################
dbg::msg( '=== localize() ===' );
#################################

assert_is( util::localize( 'Hello World.' ), "Hello World.\n" );
assert_is( util::localize( 'Hello [_1].', 'World' ), "Hello World.\n" );
assert_is( util::localize( '[_2] [_1].', 'World', 'Hello' ), "Hello World.\n" );

############################
dbg::msg( '=== debug ===' );
############################

sub main_func_noargs() { dbg::enter(); dbg::leave(); return; }
main_func_noargs();
dbg::msg( q{>> main_func_noargs() # expected} );
sub main_func_withargs( $, $ ) { dbg::enter(); dbg::leave(); return; }
main_func_withargs( 1, q{two" args} );
dbg::msg( q{>> main_func_withargs( 1, 'two" args' ) # expected} );
package dummy { sub func($) { dbg::enter(); dbg::leave(); return; } }
dummy::func( 'arg' );
dbg::msg( q{>> dummy::func( 'arg' ) # expected} );
worker->new();
dbg::msg( q{>> worker::new( 'worker' ) # expected} );
$val = testclass->new();
dbg::msg( q{>> worker::new( 'testclass' ) # expected} );
$val->run( 'arg' );
dbg::msg( q{>> testclass::run( 'arg' ) # expected} );
local @ARGV = ( 'function' );
$val = testsuperclass->new();
dbg::msg( q{>> worker::new( 'testsuperclass' ) # expected} );
$val->run();
dbg::msg( q{>> testsuperclass::run() # expected} );
dbg::msg( q{   >> util::subcommand( 'function' ) # expected} );
dbg::msg( q{   >> testsuperclass::function() # expected} );

###################################
dbg::msg( '=== argv_check() ===' );
###################################

local @ARGV = ();
assert_nothrow( "util::argv_check( 0, 0 )" );
assert_nothrow( "util::argv_check( -1, -1 )" );
assert_nothrow( "util::argv_check( -1, 0 )" );
assert_nothrow( "util::argv_check( 0, -1 )" );
assert_throw( "util::argv_check( 1, -1 )", ::colored( "Error:\n", 'red' ) . " Too few arguments.\nTry ‘gim help main’.\n" );
local @ARGV = ( 'one' );
assert_nothrow( "util::argv_check( 1, 1 )" );
assert_nothrow( "util::argv_check( -1, -1 )" );
assert_nothrow( "util::argv_check( -1, 1 )" );
assert_nothrow( "util::argv_check( 1, -1 )" );
assert_throw( "util::argv_check( 2, -1 )", ::colored( "Error:\n", 'red' ) . " Too few arguments.\nTry ‘gim help main’.\n" );
assert_throw( "util::argv_check( -1, 0 )", ::colored( "Error:\n", 'red' ) . " Too many arguments.\nTry ‘gim help main’.\n" );

#######################################
dbg::msg( '=== filespec_check() ===' );
#######################################

assert_nothrow( "util::filespec_check( 'FILE', TESTDIR . '/foo' )" );
assert_throw( "util::filespec_check( 'FILE', TESTDIR )", ::colored( "Error:\n", 'red' ) . " ‘" . TESTDIR . "’ is not a regular file.\n" ); # not found
assert_throw( "util::filespec_check( 'FILE', TESTDIR . '/bar' )", ::colored( "Error:\n", 'red' ) . " ‘" . TESTDIR . "/bar’ does not exist.\n" ); # directory
assert_throw( "util::filespec_check( 'FILE', '/dev/zero' )", ::colored( "Error:\n", 'red' ) . " ‘/dev/zero’ is not a regular file.\n" ); # character special
assert_throw( "util::filespec_check( 'FILE', '/proc/self' )", ::colored( "Error:\n", 'red' ) . " ‘/proc/self’ is not a regular file.\n" ); # symlink
assert_nothrow( "util::filespec_check( 'FILEORDIR', TESTDIR . '/foo' )" );
assert_nothrow( "util::filespec_check( 'FILEORDIR', TESTDIR )" );
assert_throw( "util::filespec_check( 'FILEORDIR', TESTDIR . '/bar' )", ::colored( "Error:\n", 'red' ) . " ‘" . TESTDIR . "/bar’ does not exist.\n" ); # not found
assert_throw( "util::filespec_check( 'FILEORDIR', '/dev/zero' )", ::colored( "Error:\n", 'red' ) . " ‘/dev/zero’ is neither regular file nor directory.\n" ); # character special
assert_throw( "util::filespec_check( 'FILEORDIR', '/proc/self' )", ::colored( "Error:\n", 'red' ) . " ‘/proc/self’ is neither regular file nor directory.\n" ); # symlink
assert_nothrow( "util::filespec_check( 'TRACKED', 'gim' )" );
assert_nothrow( "util::filespec_check( 'TRACKED', '.' )" );
assert_throw( "util::filespec_check( 'TRACKED', TESTDIR . '/foo' )", ::colored( "Error:\n", 'red' ) . " ‘" . TESTDIR . "/foo’ is not under version control.\n" );
assert_throw( "util::filespec_check( 'TRACKED', TESTDIR . '/bar' )", ::colored( "Error:\n", 'red' ) . " ‘" . TESTDIR . "/bar’ does not exist.\n" );
assert_throw( "util::filespec_check( 'TRACKED', TESTDIR )", ::colored( "Error:\n", 'red' ) . " ‘" . TESTDIR . "’ is not under version control.\n" );

###############################
dbg::msg( '=== executor ===' );
###############################

@command = ( 'nosuchcommand', 'nosucharg' );
eval { $exe = executor->new( \@command ); 1; }
    or do { assert_like( $@, qr/.*Error:\n.*Failure while executing ‘nosuchcommand nosucharg’/ ); };
@command = ( 'echo', '-e', '1\n2\n3\n4' );
$exe = executor->new( \@command );
$rc = 1;
while ( $exe->readln() )
{
    chomp;
    assert_is( $_, $rc );
    ++$rc;
}
$exe->close_exe();
assert_is( $exe->{ linecount }, 4 );
assert_is( $exe->{ rc }, 0 );
assert_is( $exe->{ errors }, '' );
@command = ( $^X, TESTDIR . '/eecho', '-e', '1\n2\n3\n4' );
$exe = executor->new( \@command );
while ( $exe->readln() ) {}
$exe->close_exe();
assert_is( $exe->{ linecount }, 0 );
assert_is( $exe->{ rc }, 0 );
assert_is( $exe->{ errors }, "1\n2\n3\n4\n" );
@command = ( 'echo', '-e', '1\n2\n3\n4' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, "1\n2\n3\n4\n" );
assert_is( $err, '' );
assert_is( $rc, 0 );
@command = ( $^X, TESTDIR . '/eecho', '-e', '1\n2\n3\n4' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, '' );
assert_is( $err, "1\n2\n3\n4\n" );
assert_is( $rc, 0 );

##########################
dbg::msg( '=== cfg ===' );
##########################

my $config_test = Config::IniFiles->new( -import => util::cfg_defaults() );

assert_is( $config_test->val( 'colorscheme', 'branch' ), 'green' );
assert_is( $config_test->val( 'colorscheme', 'current' ), 'cyan' );
assert_is( $config_test->val( 'colorscheme', 'error' ), 'red' );
assert_is( $config_test->val( 'colorscheme', 'hash' ), 'yellow' );
assert_is( $config_test->val( 'colorscheme', 'header' ), 'bold' );
assert_is( $config_test->val( 'colorscheme', 'line' ), 'magenta' );
assert_is( $config_test->val( 'colorscheme', 'local' ), 'green' );
assert_is( $config_test->val( 'colorscheme', 'name' ), 'cyan' );
assert_is( $config_test->val( 'colorscheme', 'ok' ), 'green' );
assert_is( $config_test->val( 'colorscheme', 'push' ), 'blue' );
assert_is( $config_test->val( 'colorscheme', 'ref' ), 'cyan' );
assert_is( $config_test->val( 'colorscheme', 'remote' ), 'red' );
assert_is( $config_test->val( 'colorscheme', 'stash' ), 'yellow' );
assert_is( $config_test->val( 'colorscheme', 'symref' ), 'green' );
assert_is( $config_test->val( 'colorscheme', 'tag' ), 'yellow' );
assert_is( $config_test->val( 'colorscheme', 'time' ), 'blue' );
assert_is( $config_test->val( 'colorscheme', 'upstream' ), 'yellow' );
assert_is( $config_test->val( 'colorscheme', 'url' ), 'magenta' );
assert_is( $config_test->val( 'colorscheme', 'warn' ), 'yellow' );

assert_is( $config_test->val( 'options', 'impl_info' ), '0' );

write_to_file( TESTDIR . '/testcfg.ini', "[category]\nentry=value\n[options]\ndiff=-q\n" );
$config_test = Config::IniFiles->new( -import => util::cfg_defaults(), -file => TESTDIR . '/testcfg.ini', -allowempty => 1 );

assert_is( $config_test->val( 'category', 'entry' ), 'value' );
assert_is( $config_test->val( 'options', 'diff' ), '-q' );
assert_is( $config_test->val( 'options', 'empty' ), undef );

##########################
dbg::msg( '=== fmt ===' );
##########################

assert_is( fmt::branch( 'foo' ), ::colored( 'foo' . ( ' ' x 29 ), 'green' ) );
assert_is( fmt::branch( '* foo' ), ::colored( '* foo' . ( ' ' x 27 ), 'cyan' ) );
assert_is( fmt::description( 'foo' ), 'foo' );
assert_is( fmt::error( 'foo' ), ::colored( "Error:\n", 'red' ) . ' foo' );
assert_is( fmt::hash( 'foo' ), ::colored( 'foo', 'yellow' ) );
assert_is( fmt::header( 'foo' ), ::colored( 'foo', 'bold' ) );
assert_is( fmt::linenr( 'foo' ), ::colored( 'foo', 'magenta' ) );
assert_is( fmt::local( 'foo' ), ::colored( '  foo                 ', 'green' ) );
assert_is( fmt::name( 'Long Name' ), ::colored( 'Long Name      ', 'cyan' ) );
assert_is( fmt::name( 'A really long name' ), ::colored( 'A really long n', 'cyan' ) );
assert_is( fmt::ok( 'foo' ), ::colored( "OK:\n", 'green' ) . '  foo' );
assert_is( fmt::push( 'foo' ), ::colored( 'foo', 'blue' ) );
assert_is( fmt::ref( 'foo' ), ::colored( 'foo', 'cyan' ) );
assert_is( fmt::remote( 'foo' ), ::colored( '         foo', 'red' ) );
assert_is( fmt::stash( 'foo' ), ::colored( 'foo', 'yellow' ) );
assert_is( fmt::symref( 'foo' ), ::colored( 'foo', 'green' ) );
assert_is( fmt::tag( 'foo' ), ::colored( 'foo', 'yellow' ) );
assert_is( fmt::time( 'foo' ), ::colored( '            foo', 'blue' ) );
assert_is( fmt::upstream( 'foo' ), ::colored( 'foo' . ( ' ' x 37 ), 'yellow' ) );
assert_is( fmt::url( 'foo' ), ::colored( 'foo', 'magenta' ) );
assert_is( fmt::warning( 'foo' ), ::colored( "Warning:\n", 'yellow' ) . ' foo' );

##########################
dbg::msg( '=== add ===' );
##########################

@command = ( 'git', 'init', '--bare', TESTDIR . '/repo' );
executor::run( \@command );
@command = ( 'git', 'clone', TESTDIR . '/repo', TESTDIR . '/work' );
executor::run( \@command );
$str = TESTDIR . '/work';
chdir( $str );
write_to_file( 'main.c', "int main( void )\n{\n    return 0;\n}\n" );
write_to_file( "file name with\nwhitespace", 'Funny filename business.' );
local @ARGV = ( 'main.c' );
$val = add->new();
assert_nothrow( '$val->run()' );
undef( $val );
mkdir( 'foo' );
chdir( 'foo' );
write_to_file( 'foo.c', "int foo( void )\n{\n    return 42;\n}\n" );
write_to_file( '.config', "foo = bar\n" );
chdir( '..' );
local @ARGV = ( '.' );
$val = add->new();
assert_nothrow( '$val->run()' );
undef( $val );
@command = ( 'git', 'status', '--porcelain' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, " A \"file name with\\nwhitespace\"\n A foo/.config\n A foo/foo.c\n A main.c\n" );
local @ARGV = ( 'main.c', 'foo/.config' );
$val = add->new();
assert_nothrow( '$val->run()' );
undef( $val );
@command = ( 'git', 'status', '--porcelain' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, " A \"file name with\\nwhitespace\"\n A foo/.config\n A foo/foo.c\n A main.c\n" );
local @ARGV = ( 'bar.c' );
$val = add->new();
assert_throw( '$val->run()', ::colored( "Error:\n", 'red' ) . " ‘bar.c’ does not exist.\n" );
undef( $val );
mkdir( 'bar' );
local @ARGV = ( 'bar' );
$val = add->new();
assert_nothrow( '$val->run()' );
undef( $val );

#############################
dbg::msg( '=== commit ===' );
#############################

local @ARGV = ( '-m', 'commit main.c', 'main.c' );
$val = commit->new();
assert_nothrow( '$val->run()' );
undef( $val );
@command = ( 'git', 'status', '--porcelain' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, " A \"file name with\\nwhitespace\"\n A foo/.config\n A foo/foo.c\n" );
local @ARGV = ( 'foo', '--message', 'commit foo' );
$val = commit->new();
assert_nothrow( '$val->run()' );
undef( $val );
@command = ( 'git', 'status', '--porcelain' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, " A \"file name with\\nwhitespace\"\n" );
write_to_file( 'commit_msg', 'commit all' );
local @ARGV = ( '-F', 'commit_msg' );
$val = commit->new();
assert_nothrow( '$val->run()' );
local @ARGV = ( 'bar' );
$val = commit->new();
assert_throw( '$val->run()', ::colored( "Error:\n", 'red' ) . " ‘bar’ is not under version control.\n" );
local @ARGV = ( 'baz' );
$val = commit->new();
assert_throw( '$val->run()', ::colored( "Error:\n", 'red' ) . " ‘baz’ does not exist.\n" );

############################
dbg::msg( '=== Done. ===' );
############################

say( 'Tests finished.' );
