#!/usr/bin/perl

use v5.20;

use feature      qw( signatures );
no warnings      qw( experimental::signatures );
use utf8;

unshift( @ARGV, '--debug' );

use File::Path qw( make_path remove_tree );

use constant CONFIG_DIR => $ENV{ HOME } . '/.config/gim/';
use constant PACKAGE_DIR => CONFIG_DIR . 'perl5/';
use constant TESTDIR => '.testgim.dir';

BEGIN
{
    remove_tree( TESTDIR );

    local $@ = '';
    make_path( CONFIG_DIR );

    my $rc = eval
    {
        require Carp::Assert::More;
        Carp::Assert::More->import();
        1;
    };

    if ( ! $rc )
    {
        # Pull package from GitHub to ~/.config/gim.
        make_path( PACKAGE_DIR . 'Carp/Assert' );
        system( 'curl https://raw.githubusercontent.com/petdance/carp-assert-more/refs/heads/dev/More.pm -s > ' . PACKAGE_DIR . 'Carp/Assert/More.pm' );
        use lib PACKAGE_DIR;
        require Carp::Assert::More;
        Carp::Assert::More->import();
        1;
    }
}

require './gim';

########################################

my $val;
my $exe;
my $out;
my $err;
my $rc;
my @command;

package testclass
{
    use parent -norequire => 'worker';
    sub run ( $, $ )
    {
        dbg::enter();
        dbg::leave();
        return;
    }
}

package testsuperclass
{
    use parent -norequire => 'worker';

    sub run ( $self )
    {
        dbg::enter();
        my $command = util::subcommand( 'function' );
        $self->$command();
        dbg::leave();
        return;
    }

    sub function ( $ )
    {
        dbg::enter();
        dbg::leave();
        return;
    }
}

sub assert_throw( $cmd, $msg )
{
    $cmd = $cmd . '; 1;';

    if ( eval $cmd )
    {
        $msg =~ s/\n/\\n/g;
        assert_fail( 'Exception expected: "' . $msg . '"' );
    }
    else
    {
        assert_is( $@, $msg );
    }

    return;
}

sub assert_nothrow( $cmd )
{
    $cmd = $cmd . '; 1;';

    if ( ! eval $cmd )
    {
        assert_fail( 'Unexpected exception:' . "\n" . $@ );
    }

    return;
}

sub write_to_file( $filename, $str )
{
    open( my $fh, '>', $filename ) or assert_fail( 'Opening ' . $filename . ' failed.' );
    print( $fh $str ) or assert_fail( 'Writing to ' . $filename . ' failed.' );
    close( $fh ) or assert_fail( 'I/O error on closing ' . $filename );
    undef( $fh );
    return;
}

########################################
say( 'Running tests (check gim.log).' );
########################################

mkdir( TESTDIR );
write_to_file( TESTDIR . '/foo', '' );
write_to_file( TESTDIR . '/eecho', '/usr/bin/echo $* >&2' );
@command = ( 'chmod', '+x', TESTDIR . '/eecho' );
executor::run( \@command );

##############################
dbg::msg( '=== throw() ===' );
##############################

assert_throw( "util::throw( \"Zero\\n\" )", "Error:\nZero\n" );
dbg::msg( q{>> util::localize( 'Error:' ) # expected} );
dbg::msg( q{   Error: # expected} );
dbg::msg( q{<<<<< # expected} );

#################################
dbg::msg( '=== localize() ===' );
#################################

assert_is( util::localize( 'Hello World.' ), "Hello World.\n" );
assert_is( util::localize( 'Hello [_1].', 'World' ), "Hello World.\n" );
assert_is( util::localize( '[_2] [_1].', 'World', 'Hello' ), "Hello World.\n" );

############################
dbg::msg( '=== debug ===' );
############################

sub main_func_noargs() { dbg::enter(); dbg::leave(); return; }
main_func_noargs();
dbg::msg( q{>> main_func_noargs() # expected} );
sub main_func_withargs( $, $ ) { dbg::enter(); dbg::leave(); return; }
main_func_withargs( 1, q{two" args} );
dbg::msg( q{>> main_func_withargs( 1, 'two" args' ) # expected} );
package dummy { sub func($) { dbg::enter(); dbg::leave(); return; } }
dummy::func( 'arg' );
dbg::msg( q{>> dummy::func( 'arg' ) # expected} );
worker->new();
dbg::msg( q{>> worker::new( 'worker' ) # expected} );
$val = testclass->new();
dbg::msg( q{>> worker::new( 'testclass' ) # expected} );
$val->run( 'arg' );
dbg::msg( q{>> testclass::run( 'arg' ) # expected} );
local @ARGV = ( 'function' );
$val = testsuperclass->new();
dbg::msg( q{>> worker::new( 'testsuperclass' ) # expected} );
$val->run();
dbg::msg( q{>> testsuperclass::run() # expected} );
dbg::msg( q{   >> util::subcommand( 'function' ) # expected} );
dbg::msg( q{   >> testsuperclass::function() # expected} );

###################################
dbg::msg( '=== argv_check() ===' );
###################################

local @ARGV = ();
assert_nothrow( "util::argv_check( 0, 0 )" );
assert_nothrow( "util::argv_check( -1, -1 )" );
assert_nothrow( "util::argv_check( -1, 0 )" );
assert_nothrow( "util::argv_check( 0, -1 )" );
assert_throw( "util::argv_check( 1, -1 )", "Error:\nToo few arguments.\nTry ‘gim help main’.\n" );
local @ARGV = ( 'one' );
assert_nothrow( "util::argv_check( 1, 1 )" );
assert_nothrow( "util::argv_check( -1, -1 )" );
assert_nothrow( "util::argv_check( -1, 1 )" );
assert_nothrow( "util::argv_check( 1, -1 )" );
assert_throw( "util::argv_check( 2, -1 )", "Error:\nToo few arguments.\nTry ‘gim help main’.\n" );
assert_throw( "util::argv_check( -1, 0 )", "Error:\nToo many arguments.\nTry ‘gim help main’.\n" );

#######################################
dbg::msg( '=== filespec_check() ===' );
#######################################

assert_nothrow( "util::filespec_check( 'FILE', TESTDIR . '/foo' )" );
assert_throw( "util::filespec_check( 'FILE', TESTDIR )", "Error:\n‘" . TESTDIR . "’ is not a regular file.\n" ); # not found
assert_throw( "util::filespec_check( 'FILE', TESTDIR . '/bar' )", "Error:\n‘" . TESTDIR . "/bar’ does not exist.\n" ); # directory
assert_throw( "util::filespec_check( 'FILE', '/dev/zero' )", "Error:\n‘/dev/zero’ is not a regular file.\n" ); # character special
assert_throw( "util::filespec_check( 'FILE', '/proc/self' )", "Error:\n‘/proc/self’ is not a regular file.\n" ); # symlink
assert_nothrow( "util::filespec_check( 'FILEORDIR', TESTDIR . '/foo' )" );
assert_nothrow( "util::filespec_check( 'FILEORDIR', TESTDIR )" );
assert_throw( "util::filespec_check( 'FILEORDIR', TESTDIR . '/bar' )", "Error:\n‘" . TESTDIR . "/bar’ does not exist.\n" ); # not found
assert_throw( "util::filespec_check( 'FILEORDIR', '/dev/zero' )", "Error:\n‘/dev/zero’ is neither regular file nor directory.\n" ); # character special
assert_throw( "util::filespec_check( 'FILEORDIR', '/proc/self' )", "Error:\n‘/proc/self’ is neither regular file nor directory.\n" ); # symlink
assert_nothrow( "util::filespec_check( 'TRACKED', 'gim' )" );
assert_nothrow( "util::filespec_check( 'TRACKED', '.' )" );
assert_throw( "util::filespec_check( 'TRACKED', TESTDIR . '/foo' )", "Error:\n‘" . TESTDIR . "/foo’ is not under version control.\n" );
assert_throw( "util::filespec_check( 'TRACKED', TESTDIR . '/bar' )", "Error:\n‘" . TESTDIR . "/bar’ does not exist.\n" );
assert_throw( "util::filespec_check( 'TRACKED', TESTDIR )", "Error:\n‘" . TESTDIR . "’ is not under version control.\n" );

###############################
dbg::msg( '=== executor ===' );
###############################

@command = ( 'nosuchcommand', 'nosucharg' );
eval { $exe = executor->new( \@command ); 1; }
    or do { assert_like( $@, qr/Error:\nFailure while executing ‘nosuchcommand nosucharg’/ ); };
@command = ( '/usr/bin/echo', '-e', '1\n2\n3\n4' );
$exe = executor->new( \@command );
$rc = 1;
while ( $exe->readln() )
{
    chomp;
    assert_is( $_, $rc );
    ++$rc;
}
$exe->close_exe();
assert_is( $exe->{ linecount }, 4 );
assert_is( $exe->{ rc }, 0 );
assert_is( $exe->{ errors }, '' );
@command = ( TESTDIR . '/eecho', '-e', '1\n2\n3\n4' );
$exe = executor->new( \@command );
while ( $exe->readln() ) {}
$exe->close_exe();
assert_is( $exe->{ linecount }, 0 );
assert_is( $exe->{ rc }, 0 );
assert_is( $exe->{ errors }, "1\n2\n3\n4\n" );
@command = ( '/usr/bin/echo', '-e', '1\n2\n3\n4' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, "1\n2\n3\n4\n" );
assert_is( $err, '' );
assert_is( $rc, 0 );
@command = ( TESTDIR . '/eecho', '-e', '1\n2\n3\n4' );
( $out, $err, $rc ) = executor::run( \@command );
assert_is( $out, '' );
assert_is( $err, "1\n2\n3\n4\n" );
assert_is( $rc, 0 );

############################
dbg::msg( '=== Done. ===' );
############################

say( 'Tests finished.' );
